site_name: Fangrb's cite
theme:
  name: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - config/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/core.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/latest.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/loader.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/mml-chtml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/mml-svg.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/startup.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-chtml-full-speech.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-chtml-full.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-chtml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-svg.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-svg-full.min.js

markdown_extensions:
  - attr_list
  - md_in_html
