site_name: Fangrb's cite
theme:
  name: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - md_in_html
