site_name: Fangrb's cite
theme:
  name: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - /mathjax.js
  - /katex.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
# - https://polyfill.io/v3/polyfill.min.js?features=es6

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  
